// Simple song data structure
export const songs = [
  {
    id: "twinkle",
    title: "Twinkle Twinkle Little Star",
    notes: [
      { note: "C", duration: 1 },
      { note: "C", duration: 1 },
      { note: "G", duration: 1 },
      { note: "G", duration: 1 },
      { note: "A", duration: 1 },
      { note: "A", duration: 1 },
      { note: "G", duration: 2 },
      { note: "F", duration: 1 },
      { note: "F", duration: 1 },
      { note: "E", duration: 1 },
      { note: "E", duration: 1 },
      { note: "D", duration: 1 },
      { note: "D", duration: 1 },
      { note: "C", duration: 2 },
    ],
  },
  {
    id: "happy-birthday",
    title: "Happy Birthday",
    notes: [
      { note: "C", duration: 0.5 },
      { note: "C", duration: 0.5 },
      { note: "D", duration: 1 },
      { note: "C", duration: 1 },
      { note: "F", duration: 1 },
      { note: "E", duration: 2 },
      { note: "C", duration: 0.5 },
      { note: "C", duration: 0.5 },
      { note: "D", duration: 1 },
      { note: "C", duration: 1 },
      { note: "G", duration: 1 },
      { note: "F", duration: 2 },
      { note: "C", duration: 0.5 },
      { note: "C", duration: 0.5 },
      { note: "C2", duration: 1 },
      { note: "A", duration: 1 },
      { note: "F", duration: 1 },
      { note: "E", duration: 1 },
      { note: "D", duration: 1 },
      { note: "A#", duration: 0.5 },
      { note: "A#", duration: 0.5 },
      { note: "A", duration: 1 },
      { note: "F", duration: 1 },
      { note: "G", duration: 1 },
      { note: "F", duration: 2 },
    ],
  },
  {
    id: "jingle-bells",
    title: "Jingle Bells",
    notes: [
      { note: "E", duration: 1 },
      { note: "E", duration: 1 },
      { note: "E", duration: 2 },
      { note: "E", duration: 1 },
      { note: "E", duration: 1 },
      { note: "E", duration: 2 },
      { note: "E", duration: 1 },
      { note: "G", duration: 1 },
      { note: "C", duration: 1.5 },
      { note: "D", duration: 0.5 },
      { note: "E", duration: 4 },
      { note: "F", duration: 1 },
      { note: "F", duration: 1 },
      { note: "F", duration: 1.5 },
      { note: "F", duration: 0.5 },
      { note: "F", duration: 1 },
      { note: "E", duration: 1 },
      { note: "E", duration: 1 },
      { note: "E", duration: 0.5 },
      { note: "E", duration: 0.5 },
      { note: "E", duration: 1 },
      { note: "D", duration: 1 },
      { note: "D", duration: 1 },
      { note: "E", duration: 1 },
      { note: "D", duration: 2 },
      { note: "G", duration: 2 },
    ],
  },
  {
    id: "mary-lamb",
    title: "Mary Had a Little Lamb",
    notes: [
      { note: "E", duration: 1 },
      { note: "D", duration: 1 },
      { note: "C", duration: 1 },
      { note: "D", duration: 1 },
      { note: "E", duration: 1 },
      { note: "E", duration: 1 },
      { note: "E", duration: 2 },
      { note: "D", duration: 1 },
      { note: "D", duration: 1 },
      { note: "D", duration: 2 },
      { note: "E", duration: 1 },
      { note: "G", duration: 1 },
      { note: "G", duration: 2 },
      { note: "E", duration: 1 },
      { note: "D", duration: 1 },
      { note: "C", duration: 1 },
      { note: "D", duration: 1 },
      { note: "E", duration: 1 },
      { note: "E", duration: 1 },
      { note: "E", duration: 1 },
      { note: "E", duration: 1 },
      { note: "D", duration: 1 },
      { note: "D", duration: 1 },
      { note: "E", duration: 1 },
      { note: "D", duration: 1 },
      { note: "C", duration: 2 },
    ],
  },
  {
    id: "ode-joy",
    title: "Ode to Joy",
    notes: [
      { note: "E", duration: 1 },
      { note: "E", duration: 1 },
      { note: "F", duration: 1 },
      { note: "G", duration: 1 },
      { note: "G", duration: 1 },
      { note: "F", duration: 1 },
      { note: "E", duration: 1 },
      { note: "D", duration: 1 },
      { note: "C", duration: 1 },
      { note: "C", duration: 1 },
      { note: "D", duration: 1 },
      { note: "E", duration: 1 },
      { note: "E", duration: 1.5 },
      { note: "D", duration: 0.5 },
      { note: "D", duration: 2 },
      { note: "E", duration: 1 },
      { note: "E", duration: 1 },
      { note: "F", duration: 1 },
      { note: "G", duration: 1 },
      { note: "G", duration: 1 },
      { note: "F", duration: 1 },
      { note: "E", duration: 1 },
      { note: "D", duration: 1 },
      { note: "C", duration: 1 },
      { note: "C", duration: 1 },
      { note: "D", duration: 1 },
      { note: "E", duration: 1 },
      { note: "D", duration: 1.5 },
      { note: "C", duration: 0.5 },
      { note: "C", duration: 2 },
    ],
  },
]

